/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.LoginController;
import javax.swing.JOptionPane;
/**
 *
 * @author nikes
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(Login.class.getName());

    private boolean isPasswordVisible = false;
    private char defaultEchoChar;

    public Login() {
        initComponents();
        defaultEchoChar = password_textfield.getEchoChar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainpanal = new javax.swing.JPanel();
        welcomebacktext = new javax.swing.JLabel();
        Logintocontinuetext = new javax.swing.JLabel();
        usernametext = new javax.swing.JLabel();
        Emailtext = new javax.swing.JLabel();
        passwordtext = new javax.swing.JLabel();
        forgetpassword_btn = new javax.swing.JButton();
        Login_btn = new javax.swing.JButton();
        DontHaveanaccounttext = new javax.swing.JLabel();
        registertext = new javax.swing.JButton();
        Email_textfield = new javax.swing.JTextField();
        Username_textfield = new javax.swing.JTextField();
        password_textfield = new javax.swing.JPasswordField();
        logo = new javax.swing.JLabel();
        show_hide_btn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainpanal.setBackground(new java.awt.Color(232, 255, 233));
        mainpanal.setPreferredSize(new java.awt.Dimension(1550, 840));

        welcomebacktext.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        welcomebacktext.setText("WELCOME BACK");

        Logintocontinuetext.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Logintocontinuetext.setText("Login to Continue");

        usernametext.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        usernametext.setText("User Name");

        Emailtext.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        Emailtext.setText("Email");

        passwordtext.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        passwordtext.setText("Password");

        forgetpassword_btn.setBackground(new java.awt.Color(232, 255, 233));
        forgetpassword_btn.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        forgetpassword_btn.setForeground(new java.awt.Color(255, 0, 51));
        forgetpassword_btn.setText("Forgot Password ?");
        forgetpassword_btn.addActionListener(this::forgetpassword_btnActionPerformed);

        Login_btn.setBackground(new java.awt.Color(170, 218, 172));
        Login_btn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Login_btn.setForeground(new java.awt.Color(51, 51, 51));
        Login_btn.setText("Login");
        Login_btn.addActionListener(this::Login_btnActionPerformed);

        DontHaveanaccounttext.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        DontHaveanaccounttext.setText("Don't have an account?");

        registertext.setBackground(new java.awt.Color(232, 255, 233));
        registertext.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        registertext.setForeground(new java.awt.Color(255, 102, 0));
        registertext.setText("Register");
        registertext.addActionListener(this::registertextActionPerformed);

        Email_textfield.addActionListener(this::Email_textfieldActionPerformed);

        Username_textfield.addActionListener(this::Username_textfieldActionPerformed);

        password_textfield.setText("jPasswordField2");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Logore.png"))); // NOI18N

        show_hide_btn.setText("Show/Hide");
        show_hide_btn.addActionListener(this::show_hide_btnActionPerformed);

        javax.swing.GroupLayout mainpanalLayout = new javax.swing.GroupLayout(mainpanal);
        mainpanal.setLayout(mainpanalLayout);
        mainpanalLayout.setHorizontalGroup(
            mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanalLayout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(353, 353, 353)
                        .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(welcomebacktext)
                            .addGroup(mainpanalLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(forgetpassword_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Login_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainpanalLayout.createSequentialGroup()
                                        .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Emailtext, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Logintocontinuetext, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(mainpanalLayout.createSequentialGroup()
                                                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(password_textfield)
                                                    .addComponent(passwordtext, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(show_hide_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(110, 110, 110)))))
                        .addGap(524, 524, 524))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanalLayout.createSequentialGroup()
                        .addComponent(DontHaveanaccounttext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registertext)
                        .addGap(632, 632, 632))))
        );
        mainpanalLayout.setVerticalGroup(
            mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanalLayout.createSequentialGroup()
                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanalLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(welcomebacktext, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logintocontinuetext)
                .addGap(24, 24, 24)
                .addComponent(usernametext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Emailtext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordtext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_hide_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgetpassword_btn)
                .addGap(27, 27, 27)
                .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registertext)
                    .addComponent(DontHaveanaccounttext))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgetpassword_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetpassword_btnActionPerformed
new Forgotpassword().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_forgetpassword_btnActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
       String email = Email_textfield.getText();
String password = new String(password_textfield.getPassword());

LoginController controller = new LoginController();

if (controller.login(email, password)) {

    JOptionPane.showMessageDialog(this, "Login Successful ✅");

} else {

    JOptionPane.showMessageDialog(this, "Invalid Email or Password ❌");
} // TODO add your handling code here:
    }//GEN-LAST:event_Login_btnActionPerformed

    private void Email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_textfieldActionPerformed

    private void Username_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_textfieldActionPerformed

    private void show_hide_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_hide_btnActionPerformed
if (isPasswordVisible) {

    // Hide password
    password_textfield.setEchoChar(defaultEchoChar);
    isPasswordVisible = false;

} else {

    // Show password
    password_textfield.setEchoChar((char) 0);
    isPasswordVisible = true;
}        // TODO add your handling code here:
    }//GEN-LAST:event_show_hide_btnActionPerformed

    private void registertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registertextActionPerformed
new SignUp().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_registertextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DontHaveanaccounttext;
    private javax.swing.JTextField Email_textfield;
    private javax.swing.JLabel Emailtext;
    private javax.swing.JButton Login_btn;
    private javax.swing.JLabel Logintocontinuetext;
    private javax.swing.JTextField Username_textfield;
    private javax.swing.JButton forgetpassword_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainpanal;
    private javax.swing.JPasswordField password_textfield;
    private javax.swing.JLabel passwordtext;
    private javax.swing.JButton registertext;
    private javax.swing.JButton show_hide_btn;
    private javax.swing.JLabel usernametext;
    private javax.swing.JLabel welcomebacktext;
    // End of variables declaration//GEN-END:variables
}
