/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Lenovo
 */
public class OrderHistoryPage extends javax.swing.JPanel {

    /**
     * Creates new form OrderHistoryPage
     */
    public OrderHistoryPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        navbar_product_catalog = new javax.swing.JPanel();
        Logo_productcatalog = new javax.swing.JLabel();
        ProfileBtn = new javax.swing.JButton();
        BellBtn = new javax.swing.JButton();
        CartBtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 255, 233));
        setMaximumSize(new java.awt.Dimension(1550, 840));
        setMinimumSize(new java.awt.Dimension(1550, 840));
        setPreferredSize(new java.awt.Dimension(1550, 840));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("My Orders");
        add(jLabel1);
        jLabel1.setBounds(180, 130, 240, 50);

        jPanel11.setBackground(new java.awt.Color(170, 218, 172));
        jPanel11.setLayout(new java.awt.GridLayout(0, 1, 0, 15));
        jScrollPane1.setViewportView(jPanel11);

        add(jScrollPane1);
        jScrollPane1.setBounds(180, 210, 1060, 440);

        navbar_product_catalog.setBackground(new java.awt.Color(58, 125, 68));
        navbar_product_catalog.setMinimumSize(new java.awt.Dimension(100, 48));
        navbar_product_catalog.setPreferredSize(new java.awt.Dimension(100, 88));

        Logo_productcatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/rewearLogo.jpeg"))); // NOI18N

        ProfileBtn.setBackground(new java.awt.Color(58, 125, 68));
        ProfileBtn.setForeground(new java.awt.Color(58, 125, 68));
        ProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/userrIcon.png"))); // NOI18N
        ProfileBtn.addActionListener(this::ProfileBtnActionPerformed);

        BellBtn.setBackground(new java.awt.Color(58, 125, 68));
        BellBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bellbtn.png"))); // NOI18N
        BellBtn.addActionListener(this::BellBtnActionPerformed);

        CartBtn.setBackground(new java.awt.Color(58, 125, 68));
        CartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/cartticon.png"))); // NOI18N
        CartBtn.addActionListener(this::CartBtnActionPerformed);

        javax.swing.GroupLayout navbar_product_catalogLayout = new javax.swing.GroupLayout(navbar_product_catalog);
        navbar_product_catalog.setLayout(navbar_product_catalogLayout);
        navbar_product_catalogLayout.setHorizontalGroup(
            navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_product_catalogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo_productcatalog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1082, Short.MAX_VALUE)
                .addComponent(ProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(CartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        navbar_product_catalogLayout.setVerticalGroup(
            navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_product_catalogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo_productcatalog))
                .addGap(201, 201, 201))
        );

        add(navbar_product_catalog);
        navbar_product_catalog.setBounds(0, 0, 1580, 48);

        Back.setBackground(new java.awt.Color(170, 218, 172));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(this::BackActionPerformed);
        add(Back);
        Back.setBounds(670, 740, 72, 27);
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileBtnActionPerformed

    }//GEN-LAST:event_ProfileBtnActionPerformed

    private void BellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BellBtnActionPerformed

    }//GEN-LAST:event_BellBtnActionPerformed

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed

    }//GEN-LAST:event_CartBtnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton BellBtn;
    private javax.swing.JButton CartBtn;
    private javax.swing.JLabel Logo_productcatalog;
    private javax.swing.JButton ProfileBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel navbar_product_catalog;
    // End of variables declaration//GEN-END:variables
}
