package view;

public class OrderConformation extends javax.swing.JPanel {

    // ✅ Only controller - no fields needed
    private controller.OrderConfirmationController orderController;

    // ─── Constructor 1 ────────────────────────────────────────
    public OrderConformation() {
        this(0, "Guest", -1);
    }

    // ─── Constructor 2 ────────────────────────────────────────
    public OrderConformation(int orderId, String username, int userId) {
        initComponents();
        
        // ✅ Create controller
        this.orderController = new controller
            .OrderConfirmationController(orderId, username, userId);

        // ✅ View just displays - controller provides data
        jLabel3.setText(orderController.getOrderIdText());
        
        // ✅ Log activity
        orderController.logOrderConfirmed();
    }

    // ─── Show In Frame ────────────────────────────────────────
    public void showInFrame() {
        javax.swing.JFrame frame = new javax.swing.JFrame(
            "ReWear - Order Confirmation");
        frame.setDefaultCloseOperation(
            javax.swing.JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(this);
        frame.pack();

        java.awt.Dimension screen =
            java.awt.Toolkit.getDefaultToolkit()
                .getScreenSize();
        if (screen.width < 1600 || screen.height < 900) {
            frame.setExtendedState(
                javax.swing.JFrame.MAXIMIZED_BOTH);
        } else {
            frame.setSize(1550, 840);
            frame.setLocationRelativeTo(null);
        }
        frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Logo_productcatalog = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(170, 218, 172));
        setMaximumSize(new java.awt.Dimension(1550, 840));
        setMinimumSize(new java.awt.Dimension(1550, 840));
        setPreferredSize(new java.awt.Dimension(1550, 840));
        setLayout(null);

        jPanel2.setBackground(new java.awt.Color(58, 125, 68));

        Logo_productcatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/rewearLogo.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo_productcatalog)
                .addContainerGap(1338, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(Logo_productcatalog)
                .addContainerGap())
        );

        add(jPanel2);
        jPanel2.setBounds(0, 0, 1560, 48);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 50)); // NOI18N
        jLabel1.setText("Thank You <3");
        jLabel1.setMaximumSize(new java.awt.Dimension(1550, 840));
        jLabel1.setMinimumSize(new java.awt.Dimension(1550, 840));
        jLabel1.setPreferredSize(new java.awt.Dimension(1550, 840));
        add(jLabel1);
        jLabel1.setBounds(650, 300, 450, 60);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("Your Order Has Been Placed Successfully.");
        add(jLabel2);
        jLabel2.setBounds(580, 400, 630, 40);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Order ID : ");
        add(jLabel3);
        jLabel3.setBounds(700, 460, 230, 60);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("Track your order in My Orders page & get updates in Notifications.");
        add(jLabel4);
        jLabel4.setBounds(420, 540, 920, 30);

        jButton1.setBackground(new java.awt.Color(232, 255, 233));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("View Order");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        add(jButton1);
        jButton1.setBounds(810, 700, 150, 50);

        jButton2.setBackground(new java.awt.Color(232, 255, 233));
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton2.setText("Continue Shopping");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        add(jButton2);
        jButton2.setBounds(640, 620, 220, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/tick.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(750, 100, 150, 160);

        jButton3.setBackground(new java.awt.Color(232, 255, 233));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton3.setText("Back To Home");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        add(jButton3);
        jButton3.setBounds(870, 620, 220, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Product_catalog productCatalog = new Product_catalog(
            orderController.getUsername(),
            orderController.getUserId()
        );
        productCatalog.setSize(1550, 840);
        productCatalog.setLocationRelativeTo(null);
        productCatalog.setVisible(true);

        java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // ✅ Open Order History page for this user
    OrderHistoryPage orderHistoryPage = new OrderHistoryPage(
        orderController.getUsername(),
        orderController.getUserId(),
        false                              // false = user (not admin)
    );
    
    javax.swing.JFrame frame = new javax.swing.JFrame("ReWear - My Orders");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.getContentPane().add(orderHistoryPage);
    frame.pack();
    frame.setSize(1550, 840);
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    
    // Close current Order Confirmation window
    java.awt.Window window = 
        javax.swing.SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         UserDashboard userDash = new UserDashboard(
        orderController.getUsername(),
        orderController.getUserId()
    );
    userDash.setSize(1550, 840);
    userDash.setLocationRelativeTo(null);
    userDash.setVisible(true);
    
    java.awt.Window window =
        javax.swing.SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
    }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo_productcatalog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
