package view;

import javax.swing.JOptionPane;

public class OTPpage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(OTPpage.class.getName());

 
    private final controller.ForgotPasswordController forgotController
        = new controller.ForgotPasswordController();

    private String userEmail;
    private String expectedOTP;
   

    public OTPpage() {
    initComponents();
    controller.OTPFieldHelper.setupOTPFields(
        jTextField2, jTextField3, jTextField4, jTextField5);
    this.setSize(1550, 840);
    this.setLocationRelativeTo(null);
}

public OTPpage(String email, String otp) {
    initComponents();
    this.userEmail   = email;
    this.expectedOTP = otp;
    controller.OTPFieldHelper.setupOTPFields(
        jTextField2, jTextField3, jTextField4, jTextField5);
    this.setSize(1550, 840);
    this.setLocationRelativeTo(null);
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                          
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        verify_btn = new javax.swing.JButton();
        Text8 = new javax.swing.JLabel();
        Button3 = new javax.swing.JButton();
        Logo_productcatalog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1550, 840));

        jPanel1.setBackground(new java.awt.Color(232, 255, 233));
        jPanel1.setPreferredSize(new java.awt.Dimension(1550, 840));

        Text1.setFont(new java.awt.Font("Arial Black", 1, 50)); // NOI18N
        Text1.setText("Verify OTP");

        Text3.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        Text3.setText("Enter the OTP");

        jTextField2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTextField3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jTextField4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jTextField5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        verify_btn.setBackground(new java.awt.Color(170, 218, 172));
        verify_btn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        verify_btn.setForeground(new java.awt.Color(51, 51, 51));
        verify_btn.setText("Verify Otp");
        verify_btn.addActionListener(this::verify_btnActionPerformed);

        Text8.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        Text8.setText("Didn't received OTP?");

        Button3.setBackground(new java.awt.Color(232, 255, 233));
        Button3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Button3.setForeground(new java.awt.Color(255, 0, 51));
        Button3.setText("Resend");
        Button3.addActionListener(this::Button3ActionPerformed);

        Logo_productcatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/rewearLogo.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(162, 573, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Text8)
                        .addGap(18, 18, 18)
                        .addComponent(Button3))
                    .addComponent(verify_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(643, 643, 643))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo_productcatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(496, 496, 496)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo_productcatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108)
                .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Text3)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text8)
                    .addComponent(Button3))
                .addGap(33, 33, 33)
                .addComponent(verify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 258, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void verify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify_btnActionPerformed
    String enteredOTP = controller.OTPFieldHelper.getCombinedOTP(
    jTextField2, jTextField3, jTextField4, jTextField5);

    // ✅ View checks length only
    if (enteredOTP.length() != 4) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please enter 4-digit OTP",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ✅ Controller handles verification
    int result = forgotController.verifyOTP(userEmail, enteredOTP);

    if (result == 0) {
        // ✅ Success
        javax.swing.JOptionPane.showMessageDialog(this,
            "OTP Verified Successfully!\nYou can now reset your password.",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        Resetpassword resetPage = new Resetpassword(userEmail);
        resetPage.setSize(1550, 840);
        resetPage.setLocationRelativeTo(null);
        resetPage.setVisible(true);
        this.dispose();

    } else if (result == -1) {
        // ✅ Max attempts or expired
        javax.swing.JOptionPane.showMessageDialog(this,
            "Maximum attempts reached or OTP expired!\nPlease request a new OTP.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        clearOTPFields();

    } else {
        // ✅ Wrong OTP - show remaining attempts
        javax.swing.JOptionPane.showMessageDialog(this,
            "Invalid OTP!\nYou have " + result + " attempt(s) remaining.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        clearOTPFields();
    }
    }//GEN-LAST:event_verify_btnActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
           if (userEmail == null || userEmail.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "No email found. Please go back and try again.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ✅ Controller handles resend logic
    String result = forgotController.sendOTP(userEmail);

    if (result == null) {
        // ✅ Success
        clearOTPFields();
        javax.swing.JOptionPane.showMessageDialog(this,
            "New OTP sent to: " + userEmail,
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
            result,
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    

                                    
    }//GEN-LAST:event_Button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
private void clearOTPFields() {
    controller.OTPFieldHelper.clearFields(
        jTextField2, jTextField3, jTextField4, jTextField5);
}
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OTPpage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button3;
    private javax.swing.JLabel Logo_productcatalog;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton verify_btn;
    // End of variables declaration//GEN-END:variables
}
