/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**ss
 *
 * @author LENOVO
 */
public class Product_catalog extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Product_catalog.class.getName());

    /**
     * Creates new form Product_catalog
     */
    public Product_catalog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_panal_productcatalog = new javax.swing.JPanel();
        navbar_product_catalog = new javax.swing.JPanel();
        Logo_productcatalog = new javax.swing.JLabel();
        Searchbar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Home_btn_productcatalog = new javax.swing.JButton();
        shop_btn_productcatalog = new javax.swing.JButton();
        sidepanal_productcatalog = new javax.swing.JPanel();
        Filtertext_productcatalog = new javax.swing.JLabel();
        catagotytext_productcatalog = new javax.swing.JLabel();
        women_RadioButton_productcatalog = new javax.swing.JRadioButton();
        men_RadioButton_productcatalog = new javax.swing.JRadioButton();
        children_RadioButton_productcatalog = new javax.swing.JRadioButton();
        unisex_RadioButton_productcatalog = new javax.swing.JRadioButton();
        Price_range_text_productcatalog = new javax.swing.JLabel();
        g100to500g_price_RadioButton_productcatalog = new javax.swing.JRadioButton();
        g500to1000g_price_RadioButton_productcatalog = new javax.swing.JRadioButton();
        g1000to2000g_price_RadioButton_productcatalog = new javax.swing.JRadioButton();
        g2000to5000g_price_RadioButton_productcatalog = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        panal_forscroll = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1550, 840));

        Main_panal_productcatalog.setBackground(new java.awt.Color(232, 255, 233));
        Main_panal_productcatalog.setLayout(null);

        navbar_product_catalog.setBackground(new java.awt.Color(58, 125, 68));
        navbar_product_catalog.setMinimumSize(new java.awt.Dimension(100, 48));
        navbar_product_catalog.setPreferredSize(new java.awt.Dimension(100, 88));

        Logo_productcatalog.setText("Logo");

        Searchbar.setText("Search Product");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout navbar_product_catalogLayout = new javax.swing.GroupLayout(navbar_product_catalog);
        navbar_product_catalog.setLayout(navbar_product_catalogLayout);
        navbar_product_catalogLayout.setHorizontalGroup(
            navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_product_catalogLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Logo_productcatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386)
                .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        navbar_product_catalogLayout.setVerticalGroup(
            navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Logo_productcatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Searchbar)
                .addComponent(jLabel4)
                .addComponent(jLabel5)
                .addComponent(jLabel6))
        );

        Main_panal_productcatalog.add(navbar_product_catalog);
        navbar_product_catalog.setBounds(0, 0, 1530, 48);

        Home_btn_productcatalog.setText("Home");
        Home_btn_productcatalog.addActionListener(this::Home_btn_productcatalogActionPerformed);
        Main_panal_productcatalog.add(Home_btn_productcatalog);
        Home_btn_productcatalog.setBounds(10, 60, 70, 23);

        shop_btn_productcatalog.setText("Shop");
        Main_panal_productcatalog.add(shop_btn_productcatalog);
        shop_btn_productcatalog.setBounds(90, 60, 70, 23);

        sidepanal_productcatalog.setBackground(new java.awt.Color(232, 255, 233));
        sidepanal_productcatalog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sidepanal_productcatalog.setLayout(null);

        Filtertext_productcatalog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Filtertext_productcatalog.setText("Filters");
        sidepanal_productcatalog.add(Filtertext_productcatalog);
        Filtertext_productcatalog.setBounds(10, 10, 150, 40);

        catagotytext_productcatalog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        catagotytext_productcatalog.setText("Category");
        sidepanal_productcatalog.add(catagotytext_productcatalog);
        catagotytext_productcatalog.setBounds(40, 50, 100, 30);

        women_RadioButton_productcatalog.setText("Women");
        sidepanal_productcatalog.add(women_RadioButton_productcatalog);
        women_RadioButton_productcatalog.setBounds(20, 90, 65, 21);

        men_RadioButton_productcatalog.setText("Men");
        sidepanal_productcatalog.add(men_RadioButton_productcatalog);
        men_RadioButton_productcatalog.setBounds(20, 120, 46, 21);

        children_RadioButton_productcatalog.setText("Children");
        sidepanal_productcatalog.add(children_RadioButton_productcatalog);
        children_RadioButton_productcatalog.setBounds(20, 150, 67, 21);

        unisex_RadioButton_productcatalog.setText("Unisex");
        sidepanal_productcatalog.add(unisex_RadioButton_productcatalog);
        unisex_RadioButton_productcatalog.setBounds(20, 180, 57, 21);

        Price_range_text_productcatalog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Price_range_text_productcatalog.setText("Price Range :");
        sidepanal_productcatalog.add(Price_range_text_productcatalog);
        Price_range_text_productcatalog.setBounds(10, 350, 140, 40);

        g100to500g_price_RadioButton_productcatalog.setText("100 - 500");
        sidepanal_productcatalog.add(g100to500g_price_RadioButton_productcatalog);
        g100to500g_price_RadioButton_productcatalog.setBounds(10, 430, 98, 21);

        g500to1000g_price_RadioButton_productcatalog.setText("500 - 1000");
        sidepanal_productcatalog.add(g500to1000g_price_RadioButton_productcatalog);
        g500to1000g_price_RadioButton_productcatalog.setBounds(10, 470, 79, 21);

        g1000to2000g_price_RadioButton_productcatalog.setText("1000 - 2000");
        sidepanal_productcatalog.add(g1000to2000g_price_RadioButton_productcatalog);
        g1000to2000g_price_RadioButton_productcatalog.setBounds(10, 510, 98, 21);

        g2000to5000g_price_RadioButton_productcatalog.setText("2000 - 5000");
        sidepanal_productcatalog.add(g2000to5000g_price_RadioButton_productcatalog);
        g2000to5000g_price_RadioButton_productcatalog.setBounds(10, 550, 98, 21);

        jRadioButton9.setText("5000 - 10000");
        sidepanal_productcatalog.add(jRadioButton9);
        jRadioButton9.setBounds(10, 590, 98, 21);

        Main_panal_productcatalog.add(sidepanal_productcatalog);
        sidepanal_productcatalog.setBounds(0, 100, 240, 780);

        jPanel1.setBackground(new java.awt.Color(232, 255, 233));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panal_forscroll.setBackground(new java.awt.Color(232, 255, 233));

        javax.swing.GroupLayout panal_forscrollLayout = new javax.swing.GroupLayout(panal_forscroll);
        panal_forscroll.setLayout(panal_forscrollLayout);
        panal_forscrollLayout.setHorizontalGroup(
            panal_forscrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1243, Short.MAX_VALUE)
        );
        panal_forscrollLayout.setVerticalGroup(
            panal_forscrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panal_forscroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(panal_forscroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Main_panal_productcatalog.add(jPanel1);
        jPanel1.setBounds(240, 100, 1290, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panal_productcatalog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panal_productcatalog, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_btn_productcatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_btn_productcatalogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_btn_productcatalogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Product_catalog().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Filtertext_productcatalog;
    private javax.swing.JButton Home_btn_productcatalog;
    private javax.swing.JLabel Logo_productcatalog;
    private javax.swing.JPanel Main_panal_productcatalog;
    private javax.swing.JLabel Price_range_text_productcatalog;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JLabel catagotytext_productcatalog;
    private javax.swing.JRadioButton children_RadioButton_productcatalog;
    private javax.swing.JRadioButton g1000to2000g_price_RadioButton_productcatalog;
    private javax.swing.JRadioButton g100to500g_price_RadioButton_productcatalog;
    private javax.swing.JRadioButton g2000to5000g_price_RadioButton_productcatalog;
    private javax.swing.JRadioButton g500to1000g_price_RadioButton_productcatalog;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton men_RadioButton_productcatalog;
    private javax.swing.JPanel navbar_product_catalog;
    private javax.swing.JPanel panal_forscroll;
    private javax.swing.JButton shop_btn_productcatalog;
    private javax.swing.JPanel sidepanal_productcatalog;
    private javax.swing.JRadioButton unisex_RadioButton_productcatalog;
    private javax.swing.JRadioButton women_RadioButton_productcatalog;
    // End of variables declaration//GEN-END:variables
}
