/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

public class product_details extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(
            product_details.class.getName());

    private int productId;
    private int userId;
    private String username; // ✅ Add this

    public product_details() {
        this(1, 1);
    }

    public product_details(int productId, int userId) {
        initComponents();
        this.productId = productId;
        this.userId    = userId;
        
        // ✅ Get username from DAO
        this.username = new dao.UserDAO().getUsernameById(userId);

        controller.ProductDetailController detailController =
            new controller.ProductDetailController(productId, userId);

        loadProductDetails(detailController);
        setupStarRating();
    }

    private void loadProductDetails(
            controller.ProductDetailController detailController) {

        model.Product product = detailController.getProduct();

        if (product == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Product not found!", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Product_name.setText(product.getName());
        Product_price.setText(String.valueOf(product.getPrice()));
        Size_of_product.setText(product.getCategory());
        Descriptionhere_of_product.setText(product.getDescription());

        if (product.getImagePath() != null &&
                !product.getImagePath().isEmpty()) {
            try {
                java.net.URL imgURL =
                    getClass().getResource("/" + product.getImagePath());
                if (imgURL != null) {
                    javax.swing.ImageIcon icon =
                        new javax.swing.ImageIcon(imgURL);
                    java.awt.Image scaled = icon.getImage()
                        .getScaledInstance(250, 220,
                            java.awt.Image.SCALE_SMOOTH);
                    photo.setIcon(new javax.swing.ImageIcon(scaled));
                    photo.setText("");
                }
            } catch (Exception e) {
                photo.setText("No Image");
            }
        }
    }

    private int selectedRating = 0;

    private void setupStarRating() {
        javax.swing.JLabel[] stars = {star1, star2, star3, star4, star5};

        for (int i = 0; i < stars.length; i++) {
            final int rating = i + 1;
            stars[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent e) {
                    selectedRating = rating;
                    for (int j = 0; j < stars.length; j++) {
                        if (j < rating) {
                            stars[j].setText("★");
                            stars[j].setForeground(
                                new java.awt.Color(255, 180, 0));
                        } else {
                            stars[j].setText("☆");
                            stars[j].setForeground(java.awt.Color.BLACK);
                        }
                    }
                }
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_panal_productcatalog = new javax.swing.JPanel();
        navbar_product_catalog = new javax.swing.JPanel();
        Logo_productcatalog = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        ProfileBtn = new javax.swing.JButton();
        BellBtn = new javax.swing.JButton();
        CartBtn = new javax.swing.JButton();
        Logo_productcatalog1 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        photo = new javax.swing.JLabel();
        Product_name = new javax.swing.JLabel();
        rs = new javax.swing.JLabel();
        Product_price = new javax.swing.JLabel();
        Size = new javax.swing.JLabel();
        Size_of_product = new javax.swing.JLabel();
        Add_to_cart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Descriptionhere_of_product = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Submit = new javax.swing.JButton();
        star1 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        review = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main_panal_productcatalog.setBackground(new java.awt.Color(232, 255, 233));
        Main_panal_productcatalog.setLayout(null);

        navbar_product_catalog.setBackground(new java.awt.Color(58, 125, 68));
        navbar_product_catalog.setMinimumSize(new java.awt.Dimension(100, 48));
        navbar_product_catalog.setPreferredSize(new java.awt.Dimension(100, 88));

        Logo_productcatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/rewearLogo.jpeg"))); // NOI18N

        searchBtn.setBackground(new java.awt.Color(58, 125, 68));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/search_icon.png"))); // NOI18N
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        ProfileBtn.setBackground(new java.awt.Color(58, 125, 68));
        ProfileBtn.setForeground(new java.awt.Color(58, 125, 68));
        ProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/userrIcon.png"))); // NOI18N
        ProfileBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ProfileBtn.addActionListener(this::ProfileBtnActionPerformed);

        BellBtn.setBackground(new java.awt.Color(58, 125, 68));
        BellBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/bellbtn.png"))); // NOI18N
        BellBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BellBtn.addActionListener(this::BellBtnActionPerformed);

        CartBtn.setBackground(new java.awt.Color(58, 125, 68));
        CartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/cartticon.png"))); // NOI18N
        CartBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CartBtn.addActionListener(this::CartBtnActionPerformed);

        Logo_productcatalog1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/rewearLogo.jpeg"))); // NOI18N

        javax.swing.GroupLayout navbar_product_catalogLayout = new javax.swing.GroupLayout(navbar_product_catalog);
        navbar_product_catalog.setLayout(navbar_product_catalogLayout);
        navbar_product_catalogLayout.setHorizontalGroup(
            navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_product_catalogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo_productcatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342)
                .addComponent(searchBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 779, Short.MAX_VALUE)
                .addComponent(ProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navbar_product_catalogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Logo_productcatalog1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        navbar_product_catalogLayout.setVerticalGroup(
            navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_product_catalogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navbar_product_catalogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Logo_productcatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(170, 170, 170)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(navbar_product_catalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navbar_product_catalogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Logo_productcatalog1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Main_panal_productcatalog.add(navbar_product_catalog);
        navbar_product_catalog.setBounds(0, 0, 1560, 48);

        home.setBackground(new java.awt.Color(170, 218, 172));
        home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home.setText("Home");
        home.addActionListener(this::homeActionPerformed);
        Main_panal_productcatalog.add(home);
        home.setBounds(30, 80, 100, 32);

        jButton1.setBackground(new java.awt.Color(170, 218, 172));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Shop");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        Main_panal_productcatalog.add(jButton1);
        jButton1.setBounds(150, 80, 100, 32);

        photo.setText("product_photo");
        photo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Main_panal_productcatalog.add(photo);
        photo.setBounds(230, 130, 250, 220);

        Product_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Product_name.setText("Cloth Name");
        Main_panal_productcatalog.add(Product_name);
        Product_name.setBounds(560, 120, 180, 30);

        rs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rs.setText("Rs:");
        Main_panal_productcatalog.add(rs);
        rs.setBounds(560, 160, 20, 20);

        Product_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Product_price.setText("price");
        Main_panal_productcatalog.add(Product_price);
        Product_price.setBounds(600, 160, 100, 20);

        Size.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Size.setText("Category:");
        Main_panal_productcatalog.add(Size);
        Size.setBounds(560, 190, 70, 20);

        Size_of_product.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Size_of_product.setText("Size");
        Main_panal_productcatalog.add(Size_of_product);
        Size_of_product.setBounds(630, 190, 130, 20);

        Add_to_cart.setBackground(new java.awt.Color(170, 218, 172));
        Add_to_cart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Add_to_cart.setText("ADD TO CART");
        Add_to_cart.addActionListener(this::Add_to_cartActionPerformed);
        Main_panal_productcatalog.add(Add_to_cart);
        Add_to_cart.setBounds(550, 310, 160, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Description:");
        Main_panal_productcatalog.add(jLabel1);
        jLabel1.setBounds(50, 420, 170, 30);

        Descriptionhere_of_product.setText("description here");
        Main_panal_productcatalog.add(Descriptionhere_of_product);
        Descriptionhere_of_product.setBounds(50, 460, 830, 60);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Main_panal_productcatalog.add(jSeparator1);
        jSeparator1.setBounds(0, 530, 1570, 70);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Your Review");
        Main_panal_productcatalog.add(jLabel2);
        jLabel2.setBounds(50, 550, 160, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("How would you like this product");
        Main_panal_productcatalog.add(jLabel3);
        jLabel3.setBounds(50, 590, 240, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Write your review");
        Main_panal_productcatalog.add(jLabel4);
        jLabel4.setBounds(50, 660, 230, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Main_panal_productcatalog.add(jScrollPane1);
        jScrollPane1.setBounds(70, 690, 670, 60);

        Submit.setBackground(new java.awt.Color(170, 218, 172));
        Submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(this::SubmitActionPerformed);
        Main_panal_productcatalog.add(Submit);
        Submit.setBounds(70, 760, 180, 30);

        star1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        star1.setText("☆");
        Main_panal_productcatalog.add(star1);
        star1.setBounds(70, 620, 30, 32);

        star5.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        star5.setText("☆");
        Main_panal_productcatalog.add(star5);
        star5.setBounds(230, 620, 40, 30);

        star2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        star2.setText("☆");
        Main_panal_productcatalog.add(star2);
        star2.setBounds(110, 620, 40, 30);

        star3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        star3.setText("☆");
        Main_panal_productcatalog.add(star3);
        star3.setBounds(150, 620, 40, 30);

        star4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        star4.setText("☆");
        Main_panal_productcatalog.add(star4);
        star4.setBounds(190, 620, 40, 30);

        review.setBackground(new java.awt.Color(170, 218, 172));
        review.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        review.setText("Reviews");
        review.addActionListener(this::reviewActionPerformed);
        Main_panal_productcatalog.add(review);
        review.setBounds(1010, 620, 100, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group7/rewear/arrow.png"))); // NOI18N
        Main_panal_productcatalog.add(jLabel5);
        jLabel5.setBounds(130, 90, 20, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panal_productcatalog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panal_productcatalog, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

     

    }//GEN-LAST:event_searchBtnActionPerformed

    private void ProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileBtnActionPerformed
    UserDashboard userDash = new UserDashboard(username, userId);
    userDash.setSize(1550, 840);
    userDash.setLocationRelativeTo(null);
    userDash.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ProfileBtnActionPerformed

    private void BellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BellBtnActionPerformed
      Notification_page notifPage = new Notification_page(username, userId);
    notifPage.setSize(1550, 840);
    notifPage.setLocationRelativeTo(null);
    notifPage.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BellBtnActionPerformed

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CartBtnActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed


    // ✅ Create controller
    controller.ProductDetailController detailController =
        new controller.ProductDetailController(productId, userId);

    // ✅ Send raw data to Controller
    String reviewText = jTextArea1.getText().trim();
    String result = detailController.submitReview(selectedRating, reviewText);

    if (result == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Review submitted successfully!",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Reset stars - pure UI
        jTextArea1.setText("");
        selectedRating = 0;
        javax.swing.JLabel[] stars = {star1, star2, star3, star4, star5};
        for (javax.swing.JLabel star : stars) {
            star.setText("☆");
            star.setForeground(java.awt.Color.BLACK);
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
            result, "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_SubmitActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
    UserDashboard userDash = new UserDashboard(username, userId);
        userDash.setSize(1550, 840);
        userDash.setLocationRelativeTo(null);
        userDash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Product_catalog productCatalog = new Product_catalog(username, userId);
        productCatalog.setSize(1550, 840);
        productCatalog.setLocationRelativeTo(null);
        productCatalog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewActionPerformed
     Review_page reviewPage = new Review_page(productId, userId, username);
        reviewPage.setSize(1550, 840);
        reviewPage.setLocationRelativeTo(null);
        reviewPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reviewActionPerformed

    private void Add_to_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_to_cartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_to_cartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new product_details().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_to_cart;
    private javax.swing.JButton BellBtn;
    private javax.swing.JButton CartBtn;
    private javax.swing.JLabel Descriptionhere_of_product;
    private javax.swing.JLabel Logo_productcatalog;
    private javax.swing.JLabel Logo_productcatalog1;
    private javax.swing.JPanel Main_panal_productcatalog;
    private javax.swing.JLabel Product_name;
    private javax.swing.JLabel Product_price;
    private javax.swing.JButton ProfileBtn;
    private javax.swing.JLabel Size;
    private javax.swing.JLabel Size_of_product;
    private javax.swing.JButton Submit;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel navbar_product_catalog;
    private javax.swing.JLabel photo;
    private javax.swing.JButton review;
    private javax.swing.JLabel rs;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    // End of variables declaration//GEN-END:variables
}