/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nikes
 */
public class Resetpassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(Resetpassword.class.getName());

    private String userEmail;

   
public Resetpassword() {
    initComponents();
    setupPasswordFields();
    
    this.setSize(1550, 840);
    this.setLocationRelativeTo(null);
}

public Resetpassword(String email) {
    initComponents();
    this.userEmail = email;
    setupPasswordFields();
    
    this.setSize(1550, 840);
    this.setLocationRelativeTo(null);
}

private void setupPasswordFields() {
    // New Password Field
    Newpassword_textfield.setEchoChar((char) 0);
    Newpassword_textfield.setText("********");
    Newpassword_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            String current = new String(Newpassword_textfield.getPassword());
            if (current.equals("********")) {
                Newpassword_textfield.setText("");
                Newpassword_textfield.setEchoChar('*');
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (Newpassword_textfield.getPassword().length == 0) {
                Newpassword_textfield.setEchoChar((char) 0);
                Newpassword_textfield.setText("********");
            }
        }
    });
    
    // Confirm Password Field
    Confirmpassword_textfield.setEchoChar((char) 0);
    Confirmpassword_textfield.setText("********");
    Confirmpassword_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            String current = new String(Confirmpassword_textfield.getPassword());
            if (current.equals("********")) {
                Confirmpassword_textfield.setText("");
                Confirmpassword_textfield.setEchoChar('*');
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (Confirmpassword_textfield.getPassword().length == 0) {
                Confirmpassword_textfield.setEchoChar((char) 0);
                Confirmpassword_textfield.setText("********");
            }
        }
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainpanal = new javax.swing.JPanel();
        Resetpassword_text = new javax.swing.JLabel();
        Newpassword_text = new javax.swing.JLabel();
        Newpassword_textfield = new javax.swing.JPasswordField();
        ConfirmPassword_text = new javax.swing.JLabel();
        Confirmpassword_textfield = new javax.swing.JPasswordField();
        Reset_btn = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        Logo_productcatalog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mainpanal.setBackground(new java.awt.Color(232, 255, 233));
        Mainpanal.setPreferredSize(new java.awt.Dimension(1550, 840));

        Resetpassword_text.setFont(new java.awt.Font("Arial Black", 1, 50)); // NOI18N
        Resetpassword_text.setText("Reset Password");

        Newpassword_text.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        Newpassword_text.setText("New Password");

        Newpassword_textfield.setText("jPasswordField2");
        Newpassword_textfield.addActionListener(this::Newpassword_textfieldActionPerformed);

        ConfirmPassword_text.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ConfirmPassword_text.setText("Confirm Password");

        Confirmpassword_textfield.setText("jPasswordField2");
        Confirmpassword_textfield.addActionListener(this::Confirmpassword_textfieldActionPerformed);

        Reset_btn.setBackground(new java.awt.Color(170, 218, 172));
        Reset_btn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Reset_btn.setForeground(new java.awt.Color(51, 51, 51));
        Reset_btn.setText("Reset");
        Reset_btn.addActionListener(this::Reset_btnActionPerformed);

        Logo_productcatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/rewearLogo.jpeg"))); // NOI18N

        javax.swing.GroupLayout MainpanalLayout = new javax.swing.GroupLayout(Mainpanal);
        Mainpanal.setLayout(MainpanalLayout);
        MainpanalLayout.setHorizontalGroup(
            MainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainpanalLayout.createSequentialGroup()
                .addContainerGap(564, Short.MAX_VALUE)
                .addGroup(MainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Resetpassword_text)
                    .addGroup(MainpanalLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(MainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Newpassword_textfield)
                            .addComponent(Newpassword_text, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmPassword_text, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Confirmpassword_textfield)
                            .addComponent(Reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(524, 524, 524))
            .addGroup(MainpanalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Logo_productcatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainpanalLayout.setVerticalGroup(
            MainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainpanalLayout.createSequentialGroup()
                .addGroup(MainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainpanalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Logo_productcatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(Resetpassword_text, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Newpassword_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Newpassword_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ConfirmPassword_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Confirmpassword_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mainpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mainpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Confirmpassword_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirmpassword_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirmpassword_textfieldActionPerformed

    private void Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btnActionPerformed
        String newPassword = new String(Newpassword_textfield.getPassword()).trim();
String confirmPassword = new String(Confirmpassword_textfield.getPassword()).trim();

// Remove placeholder text
if (newPassword.equals("********")) newPassword = "";
if (confirmPassword.equals("********")) confirmPassword = "";

if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Fields cannot be empty ❌");
    return;
}
// Password length validation
if (newPassword.length() < 8) {
    javax.swing.JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long!", "Weak Password", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

if (!newPassword.equals(confirmPassword)) {
    javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match ❌");
    return;
}
System.out.println("Email used: " + userEmail);
controller.ResetController controller = new controller.ResetController();

if (controller.resetPassword(userEmail, newPassword)) {

    javax.swing.JOptionPane.showMessageDialog(this, "Password Updated Successfully ✅");

    new Login().setVisible(true);
    this.dispose();

} else {

    javax.swing.JOptionPane.showMessageDialog(this, "Failed to update password ❌");
}// TODO add your handling code here:
    }//GEN-LAST:event_Reset_btnActionPerformed

    private void Newpassword_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Newpassword_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Newpassword_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Resetpassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmPassword_text;
    private javax.swing.JPasswordField Confirmpassword_textfield;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo_productcatalog;
    private javax.swing.JPanel Mainpanal;
    private javax.swing.JLabel Newpassword_text;
    private javax.swing.JPasswordField Newpassword_textfield;
    private javax.swing.JButton Reset_btn;
    private javax.swing.JLabel Resetpassword_text;
    // End of variables declaration//GEN-END:variables
}
